import Head from 'next/head'
import ProductPage from '../components/ProductPage'
import { Data } from '../services/data'

export default function Home({ cart, setCart }) {
  return (
    <div>
      <Head>
        <title>Yeshtery App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductPage data={Data} cart={cart} setCart={setCart} />
    </div>
  )
}
